
insert into TINVEST_BUSIFLAG (C_BUSIFLAG, C_BUSINAME, C_BUSIKIND, C_INVESTTYPE, C_INVESTWAY, L_FUNDDIR, L_STOCKDIR, PROCESS_ID, C_EXTCONFIG, C_TEXTTYPE)
values ('30016', '回款费用', '4', null, null, 1, null, null, '603,604', null);

insert into TINVEST_BUSIFLAG (C_BUSIFLAG, C_BUSINAME, C_BUSIKIND, C_INVESTTYPE, C_INVESTWAY, L_FUNDDIR, L_STOCKDIR, PROCESS_ID, C_EXTCONFIG, C_TEXTTYPE)
values ('30017', '回款费用(处置)', '4', null, null, 1, null, null, '602', null);

