declare
begin
delete from trepay_confirm_config;
insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (1, '01', '1', '1_1', '22108', '1', '1', '1', '0', '0', '0', '1', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (2, '01', '1', '1_1', '22084', '1', '0', '0', '1', '0', '0', '1', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (3, '01', '1', '1_1', '22086', '9', '0', '0', '0', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (4, '01', '1', '1_1', '22109', '9', '0', '0', '0', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (5, '01', '1', '1_1', '22087', '1', '1', '0', '0', '0', '0', '1', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (6, '01', '1', '1_1', '22110', '1', '1', '0', '0', '0', '0', '1', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (7, '01', '1', '1_2', '22084', '1', '0', '0', '1', '0', '0', '1', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (8, '01', '1', '1_2', '22109', '9', '0', '0', '0', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (9, '01', '1', '1_6', '22080', '9', '0', '0', '0', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (10, '01', '1', '1_6', '22108', '1', '1', '1', '0', '0', '0', '1', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (11, '01', '1', '1_6', '22086', '9', '0', '0', '0', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (12, '01', '1', '1_6', '22087', '1', '1', '0', '0', '0', '0', '1', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (13, '01', '1', '1_6', '22110', '1', '1', '0', '0', '0', '0', '1', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (14, '01', '2', '2_1', '22084', '1', '0', '0', '1', '0', '0', '1', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (15, '01', '2', '2_1', '22109', '9', '0', '0', '0', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (16, '01', '2', '2_3', '22084', '1', '0', '0', '1', '0', '0', '1', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (17, '01', '2', '2_3', '22109', '9', '0', '0', '0', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (18, '01', '2', '2_5', '22080', '9', '0', '0', '0', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (19, '01', '2', '2_5', '22108', '2', '0', '0', '1', '0', '0', '0', '1', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (20, '01', '2', '2_5', '22086', '9', '0', '0', '0', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (21, '01', '2', '2_2', '22108', '2', '0', '0', '1', '0', '0', '0', '1', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (22, '01', '2', '2_2', '22086', '9', '0', '0', '0', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (23, '01', '3', '3_1', '22111', '9', '0', '0', '0', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (24, '90', '', '', '22108', '1', '1', '1', '2', '0', '1', '1', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (25, '02', '', '5_1', '20260', '2', '0', '0', '1', '0', '1', '0', '0', '1');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (26, '02', '', '5_2', '20260', '2', '0', '0', '1', '0', '1', '0', '0', '1');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (27, '02', '', '5_3', '20260', '2', '0', '0', '1', '0', '1', '0', '0', '1');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (28, '02', '', '5_2', '20041', '9', '0', '0', '1', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (29, '02', '', '5_2', '20038', '9', '0', '0', '1', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (30, '10', '', '6_1', '22106', '9', '0', '0', '1', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (31, '10', '', '6_2', '22111', '9', '0', '0', '0', '0', '0', '0', '0', '0');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (32, '01', '1', '1_1', '20260', '2', '0', '0', '1', '0', '1', '0', '0', '1');

insert into trepay_confirm_config (L_ID, C_PROJECT_TYPE, C_RISK_TYPE, C_PROJECT_BUSITYPE, C_REPAY_TYPE, C_FORM_TYPE, C_ISLOAN, C_ISITEM, C_CONTRACT_TYPE, C_CONTRACT_REQUIRED, C_REPAY_PLAN, C_ISPROJECT, C_TRADE_STRUCTURE, C_FUND_SOURCE)
values (33, '01', '2', '2_1', '22080', '9', '0', '0', '0', '0', '0', '0', '0', '0');

end;
/
