update tmobile_config_field t set t.c_valuebound ='{"columns":[{"name":"机构名称","code":"custname","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"报价","code":"custmoney","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"联系方式","code":"custphone","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"备注","code":"custmemo","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"聘请历史","code":"hiridetail","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"评价详情","code":"custdetail","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"}]}'
where t.c_modelcode='approval/generalflow/agencyselect.htm' and t.c_fieldcode='agencytable';

update tmobile_config_field t set t.c_valuebound ='{"title":"项目信息","columns":[{"name":"项目名称","code":"projectname","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"打款单位","code":"payerCompany","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"资产包成本(元)","code":"debtamount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"资产包已回款金额(元)","code":"amount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"本次回款金额(元)","code":"famount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"}]}'
where t.c_modelcode='/financial/arrivaldata/confirmflowform.htm' and t.c_fieldcode='gridProject';

update tmobile_config_field t set t.c_valuebound ='{"title":"借款人信息","columns":[{"name":"项目名称","code":"projectname","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"户名称","code":"loanaccountname","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"初始户成本(元)","code":"loanamount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"已回款金额(元)","code":"repayamount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"冲销前挂账(元)","code":"debts","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"净回款金额(元)","code":"netrepay","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"特殊说明","code":"specialremark","fieldType":"3","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"是否处置完毕","code":"isfinished","fieldType":"5","iscanupdate":"0","valuebound":"0:否;1:是","isshow":"true"}]}'
where t.c_modelcode='/financial/arrivaldata/confirmflowform.htm' and t.c_fieldcode='gridLoan';

update tmobile_config_field t set t.c_valuebound ='{"title":"债权合同冲销信息","columns":[{"name":"债权合同编号","code":"creditorcontractcode","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"借款人名称","code":"loanaccountname","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"清收本金(元)","code":"rcorpusamount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"应收本金","code":"corpusamount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"清收利息(元)","code":"rinterest","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"应收利息","code":"interest","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"清收罚息(元)","code":"rdefaultinterest","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"应收罚息","code":"defaultinterest","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"清收复利(元)","code":"rcompoundinterest","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"应收复利","code":"compoundinterest","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"是否处置完毕","code":"isfinished","fieldType":"5","iscanupdate":"0","valuebound":"03:是;1:是;02:否;1否","isshow":"true"}]}'
where t.c_modelcode='/financial/arrivaldata/confirmflowform.htm' and t.c_fieldcode='gridCreditorContract';

update tmobile_config_field t set t.c_valuebound ='{"title":"担保人信息","columns":[{"name":"担保合同名称","code":"guaranteecontractno","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"担保金额(元)","code":"guaranteeamount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"剩余担保金额(元)","code":"repayamount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"本次回款金额(元)","code":"amount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"是否处置完毕","code":"isfinished","fieldType":5,"iscanupdate":"0","valuebound":"0:否;1:是","isshow":"true"}]}'
where t.c_modelcode='/financial/arrivaldata/confirmflowform.htm' and t.c_fieldcode='gridGuarantee';

update tmobile_config_field t set t.c_valuebound ='{"title":"收款计划信息","columns":[{"name":"计划日期","code":"pdate","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"计划本金","code":"captial","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"计划利息","code":"income","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"状态","code":"state_show","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"}]}'
where t.c_modelcode='/financial/arrivaldata/confirmflowform.htm' and t.c_fieldcode='gridPlan';

update tmobile_config_field t set t.c_valuebound ='{"title":"资金来源信息","columns":[{"name":"参与方","code":"customername","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"初始本金(元)","code":"contributionamount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"收益率(%)","code":"profitrate","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"剩余本金(元)","code":"remaincapital","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"剩余利息(元)","code":"remainincome","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"冲销金额(元)","code":"writeoffamount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"冲销方式","code":"writeofftype","fieldType":"5","iscanupdate":"0","valuebound":"1:先息后本;2:先本后息;3:利随本清;4:用户自定义","isshow":"true"},{"name":"冲销本金(元)","code":"writeoffcapital","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"冲销利息(元)","code":"writeoffincome","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"}]}'
where t.c_modelcode='/financial/arrivaldata/confirmflowform.htm' and t.c_fieldcode='gridTradeStructure';

update tmobile_config_field t set t.c_valuebound ='{"title":"保证金信息","columns":[{"name":"项目名称","code":"projectname","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"收支方向","code":"funddir","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"保证金类型","code":"deposittype_show","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"金额(元)","code":"occurbalance","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"余额(元)","code":"famount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"本方账户","code":"fundacname","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"对手方","code":"rivalname","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"对手方账户","code":"rivalaccount","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"}]}'
where t.c_modelcode='/financial/arrivaldata/confirmflowform.htm' and t.c_fieldcode='gridDeposit';

update tmobile_config_field t set t.c_valuebound ='{"title":"抵质押物信息","columns":[{"name":"抵质押物名称","code":"pawnname","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"债权合同编号","code":"creditorcontractcode","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"本次回款金额(元)","code":"amount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"是否处置完毕","code":"isfinished","fieldType":"5","iscanupdate":"0","valuebound":"0:否;1:是","isshow":"true"}]}'
where t.c_modelcode='/financial/arrivaldata/confirmflowform.htm' and t.c_fieldcode='gridPawn';

update tmobile_config_field t set t.c_valuebound ='{"title":"投资合同资金信息","columns":[{"name":"本金(元)","code":"writeoffcapital","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"利息(元)","code":"writeoffincome","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"罚息(元)","code":"penalty","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"逾期管理费(元)","code":"overduefee","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"}]}'
where t.c_modelcode='/financial/arrivaldata/confirmflowform.htm' and t.c_fieldcode='gridInvestContractRepayMent';

update tmobile_config_field t set t.c_valuebound ='{"title":"到账认领信息","columns":[{"name":"银行流水日期","code":"bankDate","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"打款单位","code":"payerCompany","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"打款银行","code":"payerBank","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"入账银行账号","code":"payeeAccount","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"金额(元)","code":"payAmount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"未认领金额(元)","code":"unClaimAmount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"认领金额(元)","code":"claimAmount","fieldType":"2","iscanupdate":"0","valuebound":"","isshow":"true"}]}'
where t.c_modelcode='/financial/arrivaldata/claimflowform.htm' and t.c_fieldcode='gridArriavlData';

update tmobile_config_field t set t.c_valuebound ='{"columns":[{"name":"备选机构","code":"officeid","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"备选推荐人","code":"lawyerid","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"报价","code":"price","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"备注","code":"memo","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"聘请历史","code":"hiridetail","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"评价详情","code":"custdetail","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"}]}'
where t.c_modelcode='approval/generalflow/officeselect.htm' and t.c_fieldcode='officetable';