
insert into TTRANSFER_SEND (C_SYSTEM, C_INTERFACEID, C_INTERFACENAME, C_USESQL, C_TRANSFERTYPE, C_VERSION, C_FILENAME, C_OUTSERVICE, C_OUTADDRESS, C_INDATATYPE, C_TABLENAME, C_BACKDATATYPE, C_BACKDATASERVICE, C_ISUSE, C_ISSAVE, C_DATASOURCE, C_TIMEOUT)
values ('AM', 'S5006', 'AM数据字典增加', null, '2', '20110831', null, null, null, '3', null, '3', null, '0', '1', null, null);

