insert into TSYS_ROLE (ROLE_CODE, ROLE_NAME, CREATOR, REMARK, PARENT_ID, ROLE_PATH, ROLE_ORDER, CREATE_DATE, MODIFY_DATE, CREATE_TIME, MODIFY_TIME, ROLE_TYPE)
values ('9998', '»œ¡ÏΩ«…´', 'admin', '', '', '', '999', 20170911, 0, 165234, 0, '');
