delete from tmobile_config_form t where t.C_FORMURL='creditorcontract/updatecreditorcontractinfobyflow.htm';
delete from tmobile_config_field t where t.C_MODELCODE='/creditorcontract/mortgageContractInfoNew.htm';
delete from tmobile_config_field t where t.C_MODELCODE='/creditorcontract/guaranteeContractInfoNew.htm';

insert into tmobile_config_form (C_FORMURL, C_FORMNAME, C_STOREBOUND, C_CONTENTBOUND, C_ISLOADATTACH, C_CLIENTTYPE, C_LOADATTCHBOUND, C_ISUSE)
values ('creditorcontract/updatecreditorcontractinfobyflow.htm', '债权信息变更', null, 'creditorContractManager.getUpdateCreditorContractForMobile()', '1', 'MOBILE', null, '1');

insert into tmobile_config_field (C_MODELCODE, C_MODELNAME, C_FIELDCODE, C_FROMFIELDCODE, C_FIELDNAME, C_FIELDTYPE, L_ORDER, C_VALUEBOUND, C_DEFVALUE, C_ALLOWBANK, L_MAXLENGTH, C_FIELDTYPENAME, C_FIELDSQLVAL)
values ('/creditorcontract/guaranteeContractInfoNew.htm', '保证合同信息', 'creditorcontract_guaranteecontract', null, '保证合同信息', '9', 1, '{"title":"保证合同信息","columns":[{"name":"是否最高额担保","code":"guaranteetype_display","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"担保方式","code":"isguaranteetype_display","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"纸质保证合同编号","code":"guaranteecontractno","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"保证人","code":"relationcode_display","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"保证金额","code":"guaranteeamount","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"剩余保证金额","code":"remainingguaranteeamount","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"币种","code":"cykind_display","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"保证期间","code":"guaranteeperiod","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"诉讼时效届满日","code":"limitationexpdate","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"保证开始日期","code":"guaranteestartdate","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"保证结束日期","code":"guaranteeenddate","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"}]}', null, null, null, '保证合同信息', null);

insert into tmobile_config_field (C_MODELCODE, C_MODELNAME, C_FIELDCODE, C_FROMFIELDCODE, C_FIELDNAME, C_FIELDTYPE, L_ORDER, C_VALUEBOUND, C_DEFVALUE, C_ALLOWBANK, L_MAXLENGTH, C_FIELDTYPENAME, C_FIELDSQLVAL)
values ('/creditorcontract/mortgageContractInfoNew.htm', '抵质押合同信息', 'creditorcontract_mortgagecontract', null, '抵质押合同信息', '9', 1, '{"title":"抵质押合同信息","columns":[{"name":"是否最高额抵质押","code":"mortgagetype_display","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"纸质抵质押合同编号","code":"mortgagecontractno","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"抵质押人","code":"mortgagorcode_display","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"抵质押开始日期","code":"mortgagestartdate","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"},{"name":"抵质押结束日期","code":"mortgageenddate","fieldType":"1","iscanupdate":"0","valuebound":"","isshow":"true"}]}', null, null, null, '抵质押合同信息', null);
